<x-app title="Settings" :active="['item' => 'settings']">

    <!-- Header page -->
    <div class="my-6 px-4 md:px-6">
        <div class="flex flex-wrap gap-2 justify-between items-center">
            <div class="w-full md:w-max">
                <h1 class="mb-1 truncate uppercase text-2xl font-bold text-gray-400 dark:text-whitee">
                    Settings company
                </h1>

                <x-breadcrumb :path="['Settings' => route('settings.account_data'), 'Company terms' => route('settings.company_terms')]" />
            </div>
        </div>
    </div>

    <section class="px-4 md:px-6">
        <x-layouts.settings active="terms">
            <h2 class="text-xl font-semibold mb-4">
                {{ 'Terms & Conditions' }}
            </h2>

            <div class="p-4 text-sm bg-gray-100 rounded dark:bg-white/10" role="alert">
                By agreeing to the Terms and Conditions you agree to accept the use of electronic documentation, including but not limited to Electronic Bill of Lading (EBOL). If you are not the Customer/Shipper, you are also affirming that you have been expressly authorized to agree on the Customer/Shipper's behalf both to the Terms and Conditions and to the use of electronic documentation, including EBOL for this shipment.
            </div>

            <textarea class="input mt-8" id="message" rows="64">
                F1 Auto Transport Inc hereinafter referred to “Transport Company” is a registered and bonded property broker (MC No. 963138). This agreement is between solely the Customer and his, her or its duly authorized agents, (hereinafter referred to as “Customer”), and F1 Auto Transport Inc(DBA F1 Auto Transport Inc).

                CONTRACT TERMS AND LIABILITY DISCLAIMER
                1. By shipper’s signature or his/her agent’s signature, or as accepted online, Transport Company and agents, jointly and separately are authorized to operate and transport vehicle[s] from the Point of Origin specified or the Point of Departure to the specified destination via a licensed, registered, bonded and insured auto carrier. Customer agrees and understands that F1 Auto Transport Inc is a registered transportation auto carrier and property broker and is acting in the capacity as such.
                2. Personal belongings are not to be transported inside the vehicle. In accordance with state and federal Department of Transportation laws, motor carriers are not licensed to transport personal cargo. The Transport Company encourages the Customer to remove personal belonging before transport. However, if the Customer needs to transport a few belongings, the Transport Company advises any personal cargo weigh less than 100 pounds, sit below the window line and remain out of the front two seats. The Transport Company and Carrier shall not be responsible for the loss or damage to personal belongings, including any “personal property” left in the vehicle, including loss or damage to stereo equipment, and to any non-stock items of the vehicle, nor will the Transport Company or Carrier be responsible for damages caused to vehicle[s] by personal property left inside vehicle.
                3. Shipper must furnish Transport Company or Carrier with necessary keys to vehicle and all compartments. Shipper is responsible for, if applicable, disarming alarm / security system by any means effective. In the event said alarm sounds and there are no keys or instructions to turn it off, Carrier may silence alarm by any means.
                4. Carrier is authorized to operate and transport Customer’s motor vehicle between its pickup location and the destination set forth on the shipping order and Bill of Lading.
                5. Customer must prepare vehicle for transport. All loose parts, fragile accessories, low hanging spoilers, etc. must be removed or secured. Customer shall remove all non-permanent, outside mounted luggage and other racks prior to shipment. Vehicles must be tendered to Carrier in good running condition [unless otherwise noted]
                with no more than a half tank of fuel (preferably 1/4 tank). Any part of the vehicle that falls off during transport is Customer’s responsibility including damages caused by said part to any vehicles[s] and/or person involved.
                6. If authorized by the Customer, Transport Company and Carrier reserve the right to engage independent sub-contractors [local transport company] to transport or ship vehicle[s] from location to terminal, and terminal to location. Such independent sub-contractors are required to have adequate insurance coverage and to provide proof of such insurance to F1 Auto Transport Inc, or to the Customer upon request. Their insurance coverage is primary and is responsible for payment of any claims for loss or damage incurred while the vehicle is in their custody and control. In the even of damage incurred while vehicle is in the care of said independent sub-contractor all resulting claims must be directed to the company who physically delivered the vehicle and not F1 Auto Transport Inc. If Carrier declines to pay for and accept any claims or loss, the Transport Company will pay for damage if the Customer chooses to select the Transport Company’s supplemental insurance policy. The policy fee starts at $99, depending on the size, make, model and value of the Customer’s vehicle. If Customer declines policy, the Transport Company will not be responsible for damage incurred. [See Additional Services] As a courtesy to our Customers, the Transport Company will, as necessary, act as agent in the claims process in order to facilitate expedient results.
                7. No delivery time is guaranteed. All delivery dates are only estimates of normal deliveries [delays may occur due to road conditions, inclement weather or mechanical issues]. Transport Company and Carrier does not agree to transport shipment in time for any particular market or event and will not be responsible for damages occurring by unavoidable delay. There are absolutely no guarantees made, expressed, or implied, regarding delivery times and dates. The Transport Company does offer guaranteed pick up with its “Guaranteed Pick Up” service option. The Transport Company requires a two-day window for pick up and delivery, in the event the Carrier faces a delay do to mechanical, road conditions or weather. The Transport Company offers guaranteed pick up for the Customer’s vehicle for an additional fee starting at $99, depending on the vehicle size, location, and time required for storage. The Transport Company will arrange for an independent sub-contractor to pick up, delivery or both and have your vehicle safely stored at a secure terminal. [See Additional Services]
                8. No auto rental will be honored [for delays, damage, or accidents]. No exceptions.
                9. Carrier will pick up and deliver as close to Customer’s door as legally and safely as possible. A mutually agreed upon place to load or unload the vehicle[s] may be necessary due to low hanging trees, low hanging wires, narrow streets and residential area restrictions.
                10. At the time of pickup, Customer and Carrier will carefully inspect the vehicle for pre-existing damage [exterior only] by completing a vehicle inspection report recorded on the Bill of Lading. Carrier and Customer will both acknowledge the condition of the vehicle and Customer will sign and receive a copy of the Bill of Lading.
                11. At the time of delivery, Customer and Carrier will carefully inspect the vehicle for possible damages incurred during transit. Carrier and Customer will both acknowledge the condition of the vehicle and Customer will sign and receive a final copy of the Bill of Lading.
                12. Damage must be noted in the proper place on the Bill of Lading and signed by Customer regardless of weather conditions, time of day or day of week. Signing the Bill of Lading and inspection report without notation of any damage verifies that Customer has received his vehicle[s] in satisfactory condition, and that F1 Auto Transport Inc/Carrier and their agents are relieved of any further responsibility. Carrier damage claims are covered by a minimum of $750,000 public liability and property damage. All claims must be submitted in writing within 24 hours of delivery. F1 Auto Transport Inc will share the Carrier insurance policy details upon request. Customer agrees that F1 Auto Transport Inc is not liable for any property damage claims to Customer’s vehicle if the Customer waives the supplemental insurance option, and that his, her or its sole remedy is against the Carrier.
                PAYMENT TERMS
                1. Shipper shall pay all cost, including storage, and additional delivery costs, incurred as a result of shippers breach of any obligation under this agreement, including inability to provide sufficient funds due, and inability to be present for accepting vehicle. Consignee agrees to meet the Carrier’s driver at specified and agreed to time and place. In the even of a payment dispute between the shipper and Consignee, the party responsible for placing this order bears 100 percent responsibility for payment of this invoice.
                2. Upon acceptance, shipper and receiver of vehicle[s], are jointly liable for all changes due for shipment. They will be responsible to pay all costs of collections, to include, but not limited to court costs and attorney’s fees with interest at a period rate of 1.5 percent each month or 18 percent each year.
                3. Consignee is responsible to be at scheduled delivery point at specified time and place. If consignee is unable to be at scheduled pick-up point, he/she will charged a $100 per day storage fee. The Transport Company and Carrier will not be held liable for any non-use of the vehicle charges, including but not limited to auto rentals, interest, or any other charges due to delay or damage to vehicle.
                4. Shipper shall pay an additional fee to be determined by the Transport Company for each inoperable vehicle. If vehicle is rendered for shipment and later becomes inoperable, the fee will be accessed, as well as any other charges incurred to accomplish delivery, including but not limited to wreckers, forklifts, roll-backs, etc.
                5. Nothing in the agreement binds carrier to pick up and/or deliver to locations from which it is impractical to operate Carrier’s equipment because of inadequacies of high way, street or passageways for loading or unloading facilities, local, state or federal.
                6. If vehicle is vandalized either during shipment or while awaiting shipment, Transport Company and Carrier will not be held responsible; owner will have to submit a claim to his/her own insurance or absorb the loss. Shipper agrees that his/her vehicle is insured and his/her insurance has primary responsibility.
                7. Payment for transport is due at or prior to time of delivery, NO exceptions.
                8. Carrier shall explicitly be entitled to and have a general lien which surveys delivery on any and all property [and documents relating thereto] of Applicant in its possessions, custody and control, en route for all sums and/or claims for outstanding and/or current charges, expenses and/or storage costs incurred by Carrier due from, arising from, or in connection with any shipment of Applicant.
                9. As outlined in Section 10761 of the Interstate Commerce Act (49 USC 10761) the payment of freight charges may not be postponed due to alleged loss or damage. These charges should be paid in full and the portion applicable to the lost or damaged item should be included in the freight claim.
                a) Claims and payment of freight charges are two entirely different transactions.
                b) ICC regulations prohibit withholding the payment of freight bills due to a pending claim. (Administrative Ruling No. 128)
                c) Without payment of the freight charges, payment for transportation has not been made. A valid claim will not be paid until freight charges are made.
                CANCELLATION AND REFUND POLICY
                1. The option to cancel a shipping order is available at any time, at no cost and with no cancellation fee, as long as the order has not yet been assigned (dispatched) to a Carrier. Our services are considered rendered when a Carrier is assigned to an order. The Customer must cancel the shipment 48 hours before scheduled pick up time in order to avoid a cancellation fee. If the Customer cancels shipment within 48 of scheduled pick up time, the deposit becomes non-refundable. If the Customer cancels shipment within 24 hours of scheduled pick up time, the deposit is non-refundable and a dry-run fee of $250 will be assessed.
                2. Refunds will be processed within 48 business hours of the cancellation request.
                3. Cancellation of an order must be submitted in writing via email sent to sales@bulldogautotransport.com or by phone call.
                4. Once a Carrier has been assigned (dispatched) to a shipping order, The Transport Company notifies Customer via email (to the email address provided at service booking).
                TRANSPORT COMPANY OR AGENTS SHALL NOT BE LIABLE FOR THE FOLLOWING:
                A. F1 Auto Transport Inc and the Carrier will not be responsible for damage caused by acts of God, hail or storm damage, or damage resulting from worn/broken parts of vehicle or added personal items.
                B. Any glass damage.
                C. Mechanical or electrical functions and damage caused by failing mechanics, electrical demise, alignment or suspension, exhaust assembly, any exhaust system, muffler, or tail pipes. No exceptions.
                D. Under carriage damage, and damage resulting from overloaded or lowered cars.
                E. Shipper is responsible for preparing vehicle for shipment. Securing lose parts, mufflers, or tail pipes, spoilers, non-stock kit additions, antennas, and switches. Any part that falls off during transport is Customer’s responsibility, as are leaking fluids, including damages caused by said parts or fluids to any and all other vehicles involved. It is the Customer’s responsibility to notify Carrier of any and all fluid leaks.
                F. DAMAGE TO VEHICLE CAUSED BY a) Vehicle that cannot be driven on or off transport truck under its own power and/or b) Vehicle having defective or insufficient brake, parking brake, or parking gear.
                G. Damage caused by freezing of engines or cooling system or batteries.
                H. Any convertible tops that are loose, torn, or show excessive wear. Bras, and/or any type of canvas covering material.
                I. The Carrier WILL NOT be responsible for damage NOT caused by driver.
                K. The Customer agrees that their vehicle is insured and their insurance company has primary responsibility. The agreement supersedes all prior writing and/or oral agreements between F1 Auto Transport Inc and the shipper may not be changed.
                1. CLAIMS. must be made in writing within 24 hours from the time of delivery. Any damage must be noted on the Bill of Lading at the time of delivery without exception. All claims for hidden damage must be made in writing and sent certified mail within 48 hours after delivery of vehicle. Hidden damage shall mean only those losses or damages to parts contained completely, within the underside of a vehicle that should require the vehicle to be hoisted on a lift in order to be viewed and identified. The party claiming hidden damage has the burden of proving the hidden damage did not exist prior to Carrier’s receipt of the vehicle[s] and that the claim relates to one for hidden damage and is otherwise proper. Pictures and two [2] estimates for repair should be sent as soon as possible. All claims are subject to a Deductible, and will be settled at actual cost.
                2. REPAIRABLE LOSSES BIDS. Shipper agrees that the amount of a claim for a repairable loss shall be established by a competitive bid process. The amount of the repairable loss shall be considered the lowest available bid amount from two [2] competing qualified automobile repair shops. Alternatively, if a Carrier elects, it may obtain an appraisal of the amount or repairable loss from an independent automobile insurance adjustment company. A qualified automobile body shop shall include any auto body shop owned by a franchised dealer or the manufacturer of the vehicle for which loss is being claimed. Carrier may, at its option, elect to accept a single bid presented by the claimant as the most effective settlement available and so elect to accept that bid as the amount of the claim. The payment by the Carrier of any claim presented by shipper shall be deemed the full and final resolution of the claim. The shipper shall release Carrier from any further liability involving the same vehicle upon payment of the claim.
                3. TOTAL LOSSES. The Carrier’s limit of liability for any total loss vehicle[s] shall be the actual cost of any verifiable expenses thereon, including Carrier’s freight charges thereon. With respect to any total loss vehicle[s], the Carrier shall not be responsible for any lost profit.
                4. VENUE. It is the intention of the parties hereto that this agreement and performance hereunder and all suites and special proceedings hereunder shall be constructed in accordance with the under pursuant to the laws of the state of Missouri [unless prompted by applicable federal law], and that any action, special proceedings, or other proceedings that my be brought arising out of, in connection with, or by reason of this agreement. The law of the state of Missouri shall be applicable [unless prompted by applicable federal law] and shall govern the exclusion if the laws of any other forum without regard to the jurisdiction in which any action or special proceedings my be initiated. Further, the parties hereby agree the venues for any action brought by either party against the other shall be in the district court for the county of Laclede, State of Missouri, and any other venue is hereby waived.
                ADDITIONAL SERVICES
                OPTIONAL SUPPLEMENTAL INSURANCE AGREEMENT
                The purpose of this Agreement is to provide the Customer with added protection in the event the Carrier fails or denies a claim to fix any damage caused by the Carrier’s own negligence with additional coverage. The Transport Company will pay damage repair and damage repair only. The policy does not provide coverage for any loss arising from Acts of God, nor does it cover damage to any personal cargo placed in the vehicle. The policy does not cover auto rental while repairs are being performed. By waiving this service, F1 Auto Transport Inc will not be responsible for any damage caused directly by the Carrier, or any claim denied by the Carrier. Please select the level of supplemental insurance you wish to purchase, or indicate you choose to decline additional supplemental coverage. The additional cost of optional supplemental insurance is non-refundable.
                ADDITIONAL SERVICES CONTINUED
                GUARANTEED PICK UP
                The purpose of this Agreement is to provide the Customer guaranteed pick up with its “Guaranteed Pick Up” service option. The Transport Company requires a two-day window for pick up and delivery, in the event the Carrier faces a delay do to mechanical, road conditions or weather. The Transport Company offers guaranteed pick up for the Customer’s vehicle for an additional fee starting at $99, depending on the vehicle size, location, and time required for storage. The Transport Company will arrange for an independent sub-contractor to pick up, deliver or both and have your vehicle safely stored at a secure terminal. If you decide the guaranteed pick up service is perfect for you, please indicate the level of service you need. If you decline guaranteed pick up service and you can not accommodate the Carrier’s two-window for pick up, the Transport Company nor the Carrier will be responsible for local transport and storage fees. The additional cost of optional guaranteed pick up service is non-refundable.
                Customers who may need more than two days of storage will be assessed a flat fee $399, which includes local transport and a weekly storage rate. If a customer needs storage for longer than a week, an additional weekly rate will be applied.

            </textarea>

        </x-layouts.settings>
    </section>

</x-app>
